name: 'Node CI Action'
description: 'Node CI action that installs node, project dependencies, makes project build and run the tests
inputs:
  node-version:
    description: ''
    required: true
    default: '20.x'
runs:
  using: "composite"
  steps:
    - name: Set up node version ${{inputs.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build

    - name: Run the tests
      run: npm run tests
